baseURL = 'https://blacksheepmeedia.com/bsm-blog/'
languageCode = 'en-us'
title = 'Black Sheep Meedia – Blog'
theme = 'PaperMod'

# Google Analytics (optional - add your tracking ID when ready)
# GoogleAnalytics = 'GA_TRACKING_ID'

[params]
  env = 'production'
  description = 'AI-powered editorial solutions and insights for modern media'
  author = 'Black Sheep Meedia Team'
  keywords = ['AI', 'media', 'editorial', 'journalism', 'content', 'automation']
  

[params.homeInfoParams]
  Title = 'Black Sheep Meedia Blog'
  Content = 'AI-powered editorial solutions and insights for modern media'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    identifier = 'website'
    name = 'Website'
    url = 'https://blacksheepmeedia.com'
    weight = 20
  [[menu.main]]
    identifier = 'website'
    name = 'Website'
    url = 'https://blacksheepmeedia.com'
    weight = 30
